package de.linogistix.mobile.processes.fuel;

public enum FuelNavigationEnum {
	FUEL_BACK_TO_MENU,
	FUEL_CHOOSE_ITEM,
	FUEL_CHOOSE_VEHICLE,
	FUEL_ENTER_AMOUNT,
	ENTER_TARGET_IN_LOC,
	ENTER_ORIGIN_LOC,
	FUEL_ENTER_DELIVERER,
	FUEL_ENTER_RECEIPIENT,
	FUEL_ENTER_ORDERTYPE,
	FUEL_ENTER_PUMP,
	FUEL_IN_COMPLETE,
	FUEL_OUT_COMPLETE,
	/*for fuel log*/
	FUEL_CHOOSE_DATES,
	FUEL_LOG_CHOOSE_LOC,
	FUEL_GET_PDF
}
