SET DEFINE OFF;
Insert into JBOSS.LOS_OUTREQ
   (ID, OUTSTATE, PARENTREQUEST_ID)
 Values
   (2003, 'RAW', 2000);
Insert into JBOSS.LOS_OUTREQ
   (ID, OUTSTATE, PARENTREQUEST_ID)
 Values
   (2007, 'RAW', 2004);
Insert into JBOSS.LOS_OUTREQ
   (ID, OUTSTATE, PARENTREQUEST_ID)
 Values
   (3153, 'RAW', 3150);
COMMIT;
