SET DEFINE OFF;
Insert into JBOSS.LOS_ORDERREQPOS
   (ID, AMOUNT, POSITIONINDEX, PARTITIONALLOWED, POSITIONSTATE, PICKEDAMOUNT, PARENTREQUEST_ID, ITEMDATA_ID)
 Values
   (2001, 30, 0, 1, 'PICKED', 30, 2000, 100);
Insert into JBOSS.LOS_ORDERREQPOS
   (ID, AMOUNT, POSITIONINDEX, PARTITIONALLOWED, POSITIONSTATE, PICKEDAMOUNT, PARENTREQUEST_ID, ITEMDATA_ID)
 Values
   (2005, 25, 0, 1, 'PICKED', 25, 2004, 100);
Insert into JBOSS.LOS_ORDERREQPOS
   (ID, AMOUNT, POSITIONINDEX, PARTITIONALLOWED, POSITIONSTATE, PICKEDAMOUNT, PARENTREQUEST_ID, ITEMDATA_ID)
 Values
   (3151, 20, 0, 1, 'PICKED', 20, 3150, 100);
COMMIT;
