SET DEFINE OFF;
Insert into JBOSS.LOS_PICKREQ
   (ID, CUSTOMERNUMBER, STATE, PARENTREQUEST_ID, DESTINATION_ID, USER_ID)
 Values
   (2002, 'System', 'FINISHED', 2000, 1458, 0);
Insert into JBOSS.LOS_PICKREQ
   (ID, CUSTOMERNUMBER, STATE, PARENTREQUEST_ID, DESTINATION_ID, USER_ID)
 Values
   (2006, 'System', 'FINISHED', 2004, 1458, 0);
Insert into JBOSS.LOS_PICKREQ
   (ID, CUSTOMERNUMBER, STATE, PARENTREQUEST_ID, DESTINATION_ID, USER_ID)
 Values
   (3152, 'System', 'FINISHED', 3150, 1458, 0);
COMMIT;
