SET DEFINE OFF;
Insert into JBOSS.LOS_UNITLOAD
   (ID, STOCKTAKINGDATE, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (2250, TO_TIMESTAMP('20/11/2012 9:38:44.806000 лл','fmDDfm/fmMMfm/YYYY fmHH12fm:MI:SS.FF AM'), 'MIXED', 0);
Insert into JBOSS.LOS_UNITLOAD
   (ID, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (2251, 'MIXED', 0);
Insert into JBOSS.LOS_UNITLOAD
   (ID, STOCKTAKINGDATE, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (2252, TO_TIMESTAMP('20/11/2012 9:42:38.263000 лл','fmDDfm/fmMMfm/YYYY fmHH12fm:MI:SS.FF AM'), 'MIXED', 0);
Insert into JBOSS.LOS_UNITLOAD
   (ID, STOCKTAKINGDATE, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (3300, TO_TIMESTAMP('21/11/2012 8:02:02.330000 лл','fmDDfm/fmMMfm/YYYY fmHH12fm:MI:SS.FF AM'), 'MIXED', 0);
Insert into JBOSS.LOS_UNITLOAD
   (ID, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (1700, 'OF_SAME_LOT_CONSOLIDATE', 1450);
Insert into JBOSS.LOS_UNITLOAD
   (ID, PACKAGETYPE, STORAGELOCATION_ID)
 Values
   (2750, 'OF_SAME_LOT_CONSOLIDATE', 1450);
COMMIT;
